# .github/workflows/main.yml

on:
  schedule:
  - cron: '0 12 * * *' # every day at noon

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: lucasff.guanabara@gmail.com # replace me
        MAX_DAYS: 16
        MIN_COMMITS_PER_DAY: 3
        MAX_COMMITS_PER_DAY: 7
